name: projectUno_$(Date:yyyyMMdd)$(Rev:.r)

image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - test
  - build

build-job:
  stage: build
  script:
    - echo "Building file"

test-job:
  stage: test
  script:
    - echo "Running tests"
    - dotnet test





