// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Persistence.Data;

#nullable disable

namespace MyApp.Persistence.Migrations
{
    [DbContext(typeof(VueTS_ASPdotNetContext))]
    [Migration("20230721124500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Persistence.Models.CardDbDTO", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int>("ActiveColour")
                        .HasColumnType("int");

                    b.Property<int>("ActiveValue")
                        .HasColumnType("int");

                    b.Property<int?>("DeckDbDTODeckId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("DeckDbDTODeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MyApp.Persistence.Models.DeckDbDTO", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeckId"));

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeckId");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("MyApp.Persistence.Models.PlayerDbDTO", b =>
                {
                    b.Property<int>("PlayerNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerNameId"));

                    b.Property<int?>("DeckDbDTODeckId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerNameId");

                    b.HasIndex("DeckDbDTODeckId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MyApp.Persistence.Models.CardDbDTO", b =>
                {
                    b.HasOne("MyApp.Persistence.Models.DeckDbDTO", null)
                        .WithMany("Deck")
                        .HasForeignKey("DeckDbDTODeckId");
                });

            modelBuilder.Entity("MyApp.Persistence.Models.PlayerDbDTO", b =>
                {
                    b.HasOne("MyApp.Persistence.Models.DeckDbDTO", null)
                        .WithMany("PlayerList")
                        .HasForeignKey("DeckDbDTODeckId");
                });

            modelBuilder.Entity("MyApp.Persistence.Models.DeckDbDTO", b =>
                {
                    b.Navigation("Deck");

                    b.Navigation("PlayerList");
                });
#pragma warning restore 612, 618
        }
    }
}
